name: dependabot-auto-merge
on:
  pull_request:

permissions: {}

jobs:
  auto-merge:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge PR
        if: contains(fromJSON('["docker", "github_actions"]'), steps.metadata.outputs.package-ecosystem)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          gh pr checks "$PR_NUMBER" --required --watch --fail-fast --interval 30
          gh pr merge "$PR_NUMBER" --squash --match-head-commit "$HEAD_SHA"
          gh workflow run tag-release-actions.yml --ref "$DEFAULT_BRANCH"
