name: deploy-rollback
on:
  workflow_call:
    inputs:
      NAIS_RESOURCE:
        required: true
        type: string
        default: "nais.yml"
      NAIS_VARS:
        required: true
        type: string
        default: "naiserator-dev.json"
      CLUSTER:
        required: true
        type: string
        default: 'dev-gcp'
      VERSION:
        required: true
        type: string
        default: "latest"
      TEAM:
        required: true
        default: teampam
        type: string

jobs:
  deploy-rollback:
    permissions:
      contents: read
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "VERSION_TAG=${{ inputs.VERSION }}" >> $GITHUB_ENV
          echo "IMAGE=europe-north1-docker.pkg.dev/${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}/${{ inputs.TEAM }}/${{ github.event.repository.name }}:${{ inputs.VERSION }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.VERSION_TAG }}
      - uses: nais/deploy/actions/deploy@v2
        name: deploy to ${{ inputs.CLUSTER }}
        env:
          CLUSTER: ${{ inputs.CLUSTER }}
          RESOURCE: ${{ inputs.NAIS_RESOURCE }}
          VARS: ${{ inputs.NAIS_VARS }}
