on:
  workflow_call:
    inputs:
      LANGUAGE:
        required: false
        type: string
        default: "java"
      JAVA_DISTRIBUTION:
        required: false
        type: string
        default: "temurin"
      JAVA_VERSION:
        required: false
        type: string
        default: "14"
      NODE_VERSION:
        required: false
        type: string
        default: "14"
      BUILD_CACHE:
        required: false
        type: string
        default: "gradle"
      NAIS_RESOURCE:
        required: false
        type: string
        default: "naiserator.yml"
      NAIS_VARS:
        required: false
        type: string
        default: "naiserator-dev.json"
      BUILD_SCRIPT:
        required: false
        type: string
        default: "./build.sh"
    secrets:
      NAIS_DEPLOY_APIKEY:
        required: true
      NAIS_WORKLOAD_IDENTITY_PROVIDER:
        required: true
      SNYK_TOKEN:
        required: false
      OPTIONAL_SECRET:
        required: false
jobs:
  build-and-deploy-feature:
    runs-on: ubuntu-latest
    environment: dev-gcp
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx
      - name: Setup java
        if: ${{ inputs.LANGUAGE == 'java' }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
          java-version: ${{ inputs.JAVA_VERSION }}
          cache: ${{ inputs.BUILD_CACHE }}
      - name: Setup Node
        if: ${{ inputs.LANGUAGE == 'node' }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: ${{ inputs.BUILD_CACHE }}
      - name: Build and test
        run: |
          ${{ inputs.BUILD_SCRIPT }}
        env:
          OPTIONAL_SECRET: ${{ secrets.OPTIONAL_SECRET }}
      - uses: docker/login-action@v2
        name: Docker login
        with:
          registry: ghcr.io
          username: ${{ github.REPOSITORY }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker image and version name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          APPLICATION=$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)
          VERSION_TAG=${GITHUB_REF##*/}-$SHORT_SHA
          IMAGE=ghcr.io/$GITHUB_REPOSITORY:$VERSION_TAG
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teampam
          tag: ${{ env.IMAGE }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          build_secrets: |
            "optional_secret=${{ secrets.OPTIONAL_SECRET }}"
      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            "optional_secret=${{ secrets.OPTIONAL_SECRET }}"
        env:
          OPTIONAL_SECRET: ${{ secrets.OPTIONAL_SECRET }}
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: ${{ inputs.NAIS_RESOURCE }}
          VARS: ${{ inputs.NAIS_VARS }}
