on:
  workflow_call:
    inputs:
      LANGUAGE:
        required: false
        type: string
        default: "java"
      CODEQL_ENABLED:
        required: false
        type: boolean
        default: true
      TEAM:
        required: false
        type: string
        default: "teampam"
      JAVA_DISTRIBUTION:
        required: false
        type: string
        default: "temurin"
      JAVA_VERSION:
        required: false
        type: string
        default: "14"
      NODE_VERSION:
        required: false
        type: string
        default: "14"
      BUILD_CACHE:
        required: false
        type: string
        default: "gradle"
      NAIS_RESOURCE:
        required: false
        type: string
        default: "naiserator.yml"
      NAIS_VARS:
        required: false
        type: string
        default: "naiserator-dev.json"
      CLUSTER:
        required: false
        type: string
        default: "dev-gcp"
      BUILD_SCRIPT:
        required: false
        type: string
        default: "./build.sh"
      WORKING_DIRECTORY:
        required: false
        type: string
        default: "./"
      IMAGE_SUFFIX:
        required: false
        type: string
    secrets:
      NAIS_DEPLOY_APIKEY:
        required: true
      SNYK_TOKEN:
        required: false
      OPTIONAL_SECRET:
        required: false
      NAIS_WORKLOAD_IDENTITY_PROVIDER:
        required: true
      CODEQL_EXTERNAL_REPO_TOKEN:
        required: false
jobs:
  deploy-dev:
    permissions:
      contents: write
      id-token: write
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    environment: ${{ inputs.CLUSTER }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx
      - name: Setup CodeQL
        if: ${{ inputs.CODEQL_ENABLED }}
        uses: github/codeql-action/init@v2
        with:
          external-repository-token: ${{ secrets.GITHUB_TOKEN }}
          languages: ${{ (inputs.LANGUAGE == 'node' && 'javascript') || inputs.LANGUAGE }}
      - name: Setup java
        if: ${{ inputs.LANGUAGE == 'java' }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
          java-version: ${{ inputs.JAVA_VERSION }}
          cache: ${{ inputs.BUILD_CACHE }}
      - name: Setup Node
        if: ${{ inputs.LANGUAGE == 'node' }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: ${{ inputs.BUILD_CACHE }}
      - name: Build and test
        run: |
          ${{ inputs.BUILD_SCRIPT }}
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        env:
          OPTIONAL_SECRET: ${{ secrets.OPTIONAL_SECRET }}
      - name: Perform CodeQL Analysis
        if: ${{ inputs.CODEQL_ENABLED }}
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{ (inputs.LANGUAGE == 'node' && 'javascript') || inputs.LANGUAGE }}"
      - name: Pre-deploy
        uses: navikt/pam-deploy/actions/pre-deploy@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          TEAM: ${{ inputs.TEAM }}
          IMAGE_SUFFIX: ${{ inputs.IMAGE_SUFFIX }}
      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: ${{ inputs.TEAM }}
          tag: ${{ env.VERSION_TAG }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          dockerfile: "${{ inputs.WORKING_DIRECTORY }}Dockerfile"
          image_suffix: ${{ inputs.IMAGE_SUFFIX }}
          build_secrets: |
            "optional_secret=${{ secrets.OPTIONAL_SECRET }}"
      - name: Deploy to ${{ inputs.CLUSTER }}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.CLUSTER }}
          RESOURCE: ${{ inputs.NAIS_RESOURCE }}
          VARS: ${{ inputs.NAIS_VARS }}
      - name: Post-deploy
        uses: navikt/pam-deploy/actions/post-deploy@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Draft release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.VERSION_TAG }}
          name: ${{ env.DRAFT_NAME }}
          body: ${{ env.CHANGE_LOG }}
          draft: true
          prerelease: false
