on:
  workflow_call:
    inputs:
      LANGUAGE:
        required: false
        type: string
        default: "java"
      SNYK_ENABLED:
        required: false
        type: boolean
        default: true
      SNYK_ORG:
        required: false
        type: string
        default: "teampam"
      JAVA_DISTRIBUTION:
        required: false
        type: string
        default: "temurin"
      JAVA_VERSION:
        required: false
        type: string
        default: "14"
      NODE_VERSION:
        required: false
        type: string
        default: "14"
      BUILD_CACHE:
        required: false
        type: string
        default: "gradle"
      NAIS_RESOURCE:
        required: false
        type: string
        default: "naiserator.yml"
      NAIS_VARS:
        required: false
        type: string
        default: "naiserator-dev.json"
    secrets:
      NAIS_DEPLOY_APIKEY:
        required: true
      SNYK_TOKEN:
        required: true
      OPTIONAL_SECRET:
        required: false
jobs:
  build-and-deploy-feature:
    runs-on: ubuntu-latest
    environment: dev-gcp
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/setup@master
      - name: Setup java
        if: ${{ inputs.LANGUAGE == 'java' }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
          java-version: ${{ inputs.JAVA_VERSION }}
          cache: ${{ inputs.BUILD_CACHE }}
      - name: Setup Node
        if: ${{ inputs.LANGUAGE == 'node' }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: ${{ inputs.BUILD_CACHE }}
      - name: Build and test
        run: |
          ./build.sh
        env:
          OPTIONAL_SECRET: ${{ secrets.OPTIONAL_SECRET }}
      - name: Snyk test
        if: ${{ inputs.SNYK_ENABLED }}
        run: snyk test --org=${{ inputs.SNYK_ORG }} --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - uses: docker/login-action@v2
        name: Docker login
        with:
          registry: ghcr.io
          username: ${{ github.REPOSITORY }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          APPLICATION=$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)
          VERSION_TAG=${GITHUB_REF##*/}-$SHORT_SHA
          IMAGE=ghcr.io/$GITHUB_REPOSITORY:$VERSION_TAG
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build . --pull -t $IMAGE
          echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin ghcr.io
          docker push $IMAGE
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: ${{ inputs.NAIS_RESOURCE }}
          VARS: ${{ inputs.NAIS_VARS }}