name: deploy-rollback
on:
  workflow_call:
    inputs:
      NAIS_RESOURCE:
        type: string
        required: true
        default: "nais.yml"
      NAIS_VARS:
        type: string
        required: true
        default: "naiserator-dev.json"
      CLUSTER:
        type: string
        default: 'dev-gcp'
      VERSION:
        required: true
        type: string
      TEAM:
        default: teampam
        type: string
env:
  VERSION_TAG: ${{ inputs.VERSION }}
  IMAGE: europe-north1-docker.pkg.dev/${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}/${{ inputs.TEAM }}/${{ github.event.repository.name }}:${{ inputs.VERSION }}
jobs:
  deploy-rollback:
    permissions:
      contents: read
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.VERSION_TAG }}
      - uses: nais/deploy/actions/deploy@v2
        name: deploy to ${{ inputs.CLUSTER }}
        env:
          CLUSTER: ${{ inputs.CLUSTER }}
          RESOURCE: ${{ inputs.NAIS_RESOURCE }}
          VARS: ${{ inputs.NAIS_VARS }}
