name: deploy-rollback
on:
  workflow_call:
    inputs:
      NAIS_RESOURCE:
        required: false
        type: string
        default: "naiserator.yml"
      NAIS_VARS:
        required: false
        type: string
        default: "naiserator-prod.json"
      CLUSTER:
        required: false
        type: string
        default: 'dev-gcp'
      VERSION:
        required: false
        type: string
        default: "latest"
      TEAM:
        required: false
        default: teampam
        type: string

jobs:
  deploy-rollback:
    permissions:
      contents: read
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Set environment variables
        env:
          INPUT_VERSION: ${{ inputs.VERSION }}
          INPUT_TEAM: ${{ inputs.TEAM }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          echo "VERSION_TAG=$INPUT_VERSION" >> "$GITHUB_ENV"
          echo "IMAGE=europe-north1-docker.pkg.dev/nais-management-233d/$INPUT_TEAM/$REPO_NAME:$INPUT_VERSION" >> "$GITHUB_ENV"
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ env.VERSION_TAG }}
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@v2
        name: deploy to ${{ inputs.CLUSTER }}
        env:
          CLUSTER: ${{ inputs.CLUSTER }}
          RESOURCE: ${{ inputs.NAIS_RESOURCE }}
          VARS: ${{ inputs.NAIS_VARS }}
