on:
  workflow_call:
    inputs:
      NAIS_RESOURCE:
        required: false
        type: string
        default: "naiserator.yml"
      NAIS_VARS:
        required: false
        type: string
        default: "naiserator-prod.json"
      CLUSTER:
        required: false
        type: string
        default: "prod-gcp"
      TEAM:
        required: false
        type: string
        default: "teampam"
      IMAGE_SUFFIX:
        required: false
        type: string
      VERSION_TAG:
        required: false
        type: string

env:
  VERSION_TAG: ${{ inputs.VERSION_TAG || github.event.release.tag_name }}

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: ${{ inputs.CLUSTER }}
    concurrency:
      group: deploy-${{ inputs.CLUSTER }}-${{ inputs.IMAGE_SUFFIX || github.repository }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ env.VERSION_TAG }}
          persist-credentials: false
      - name: pre-production
        uses: navikt/pam-deploy/actions/pre-production@v9
        env:
          TEAM: ${{ inputs.TEAM }}
          IMAGE_SUFFIX: ${{ inputs.IMAGE_SUFFIX }}
      - uses: nais/deploy/actions/deploy@v2
        name: deploy to ${{ inputs.CLUSTER }}
        env:
          CLUSTER: ${{ inputs.CLUSTER }}
          RESOURCE: ${{ inputs.NAIS_RESOURCE }}
          VARS: ${{ inputs.NAIS_VARS }}
      - name: post-production
        uses: navikt/pam-deploy/actions/post-production@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_SUFFIX: ${{ inputs.IMAGE_SUFFIX }}
