on:
  workflow_call:
    inputs:
      NAIS_RESOURCE:
        required: false
        type: string
        default: "naiserator.yml"
      CLUSTER:
        required: false
        type: string
        default: "dev-gcp"
      VAR:
        required: false
        type: string
      VARS:
        required: false
        type: string
    secrets:
      NAIS_DEPLOY_APIKEY:
        required: true
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: ${{ inputs.CLUSTER }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get documentation contentfile
        run: |
          gh api -H "Accept: application/vnd.github.v3.raw" /repos/navikt/pam-doc/contents/README.md
          gh api -H "Accept: application/vnd.github+json" /repos/navikt/pam-repoinfo/contents/repos.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Documentation
        uses: navikt/pam-deploy/actions/documentation@v2
        env:
          CLUSTER: ${{ inputs.CLUSTER }}
          RESOURCE: ${{ inputs.NAIS_RESOURCE }}
          VAR: ${{ inputs.VAR }}
          VARS: ${{ inputs.VARS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}