name: zizmor GitHub Actions security analysis
on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/**"
      - "actions/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "actions/**"
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  zizmor:
    name: zizmor latest via uv
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      security-events: write # upload SARIF to code scanning
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - name: Run zizmor
        run: uvx zizmor --format sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@7188fc363630916deb702c7fdcf4e481b751f97a # v4
        with:
          sarif_file: results.sarif
          category: zizmor
